from scripts.yaml_io import read_yaml
from scripts.extract_gb_info import get_locus
from scripts.import_user_data import Data


workdir: "../results/"


sample_data: Data = Data("../user_metadata/sample_data.csv")
(
    paired_illumina,
    single_illumina,
    ont_samples,
    sample_info_dic,
) = sample_data.get_options()

print(
    paired_illumina,
    single_illumina,
    ont_samples,
    sample_info_dic,
)

user_metadata = read_yaml("../user_metadata/sample_data.yaml")
PROJECT_NAME = user_metadata["project_name"]
REFERENCE_FASTA = user_metadata["fasta_reference"]
REFERENCE_GB = user_metadata["gb_reference"]
REFERENCE_NAME = re.findall("(?<=references/)(.*?)(?=.fasta)", REFERENCE_FASTA)[0]
SEGMENTS = get_locus(REFERENCE_GB)

print("Project name: " + PROJECT_NAME)
