identification: MN908947
locus:
- SARS_CoV_2
project: SARS_CoV_2_80snps
proteins:
- orf1ab
- S
- ORF3a
- E
- M
- ORF6
- ORF7a
- ORF8
- N
- ORF10
sample_type: null
samples:
  sample_10__80snps_SARS_CoV_2:
    fastq1: sample_10__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_10__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_11__80snps_SARS_CoV_2:
    fastq1: sample_11__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_11__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_12__80snps_SARS_CoV_2:
    fastq1: sample_12__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_12__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_13__80snps_SARS_CoV_2:
    fastq1: sample_13__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_13__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_14__80snps_SARS_CoV_2:
    fastq1: sample_14__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_14__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_15__80snps_SARS_CoV_2:
    fastq1: sample_15__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_15__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_16__80snps_SARS_CoV_2:
    fastq1: sample_16__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_16__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_17__80snps_SARS_CoV_2:
    fastq1: sample_17__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_17__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_18__80snps_SARS_CoV_2:
    fastq1: sample_18__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_18__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_19__80snps_SARS_CoV_2:
    fastq1: sample_19__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_19__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__80snps_SARS_CoV_2:
    fastq1: sample_1__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_20__80snps_SARS_CoV_2:
    fastq1: sample_20__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_20__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_21__80snps_SARS_CoV_2:
    fastq1: sample_21__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_21__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_22__80snps_SARS_CoV_2:
    fastq1: sample_22__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_22__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_23__80snps_SARS_CoV_2:
    fastq1: sample_23__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_23__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_24__80snps_SARS_CoV_2:
    fastq1: sample_24__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_24__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_25__80snps_SARS_CoV_2:
    fastq1: sample_25__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_25__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_26__80snps_SARS_CoV_2:
    fastq1: sample_26__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_26__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_27__80snps_SARS_CoV_2:
    fastq1: sample_27__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_27__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_28__80snps_SARS_CoV_2:
    fastq1: sample_28__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_28__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_29__80snps_SARS_CoV_2:
    fastq1: sample_29__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_29__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__80snps_SARS_CoV_2:
    fastq1: sample_2__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_30__80snps_SARS_CoV_2:
    fastq1: sample_30__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_30__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_3__80snps_SARS_CoV_2:
    fastq1: sample_3__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_3__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_4__80snps_SARS_CoV_2:
    fastq1: sample_4__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_4__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_5__80snps_SARS_CoV_2:
    fastq1: sample_5__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_5__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_6__80snps_SARS_CoV_2:
    fastq1: sample_6__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_6__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_7__80snps_SARS_CoV_2:
    fastq1: sample_7__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_7__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_8__80snps_SARS_CoV_2:
    fastq1: sample_8__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_8__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_9__80snps_SARS_CoV_2:
    fastq1: sample_9__80snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_9__80snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
version: '3'
