identification: MN908947
locus:
- SARS_CoV_2
project: SARS_CoV_2_70identity
proteins:
- orf1ab
- S
- ORF3a
- E
- M
- ORF6
- ORF7a
- ORF8
- N
- ORF10
sample_type: null
samples:
  sample_10__70identity_SARS_CoV_2:
    fastq1: sample_10__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_10__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_11__70identity_SARS_CoV_2:
    fastq1: sample_11__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_11__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_12__70identity_SARS_CoV_2:
    fastq1: sample_12__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_12__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_13__70identity_SARS_CoV_2:
    fastq1: sample_13__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_13__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_14__70identity_SARS_CoV_2:
    fastq1: sample_14__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_14__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_15__70identity_SARS_CoV_2:
    fastq1: sample_15__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_15__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_16__70identity_SARS_CoV_2:
    fastq1: sample_16__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_16__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_17__70identity_SARS_CoV_2:
    fastq1: sample_17__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_17__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_18__70identity_SARS_CoV_2:
    fastq1: sample_18__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_18__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_19__70identity_SARS_CoV_2:
    fastq1: sample_19__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_19__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__70identity_SARS_CoV_2:
    fastq1: sample_1__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_20__70identity_SARS_CoV_2:
    fastq1: sample_20__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_20__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_21__70identity_SARS_CoV_2:
    fastq1: sample_21__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_21__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_22__70identity_SARS_CoV_2:
    fastq1: sample_22__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_22__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_23__70identity_SARS_CoV_2:
    fastq1: sample_23__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_23__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_24__70identity_SARS_CoV_2:
    fastq1: sample_24__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_24__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_25__70identity_SARS_CoV_2:
    fastq1: sample_25__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_25__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_26__70identity_SARS_CoV_2:
    fastq1: sample_26__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_26__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_27__70identity_SARS_CoV_2:
    fastq1: sample_27__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_27__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_28__70identity_SARS_CoV_2:
    fastq1: sample_28__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_28__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_29__70identity_SARS_CoV_2:
    fastq1: sample_29__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_29__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__70identity_SARS_CoV_2:
    fastq1: sample_2__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_30__70identity_SARS_CoV_2:
    fastq1: sample_30__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_30__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_3__70identity_SARS_CoV_2:
    fastq1: sample_3__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_3__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_4__70identity_SARS_CoV_2:
    fastq1: sample_4__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_4__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_5__70identity_SARS_CoV_2:
    fastq1: sample_5__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_5__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_6__70identity_SARS_CoV_2:
    fastq1: sample_6__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_6__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_7__70identity_SARS_CoV_2:
    fastq1: sample_7__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_7__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_8__70identity_SARS_CoV_2:
    fastq1: sample_8__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_8__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_9__70identity_SARS_CoV_2:
    fastq1: sample_9__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_9__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
version: '3'
