identification: MN908947
locus:
- SARS_CoV_2
project: SARS_CoV_2
proteins:
- orf1ab
- S
- ORF3a
- E
- M
- ORF6
- ORF7a
- ORF8
- N
- ORF10
samples:
  sample_1__100identity_SARS_CoV_2:
    fastq1: sample_1__100identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__100identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__50identity_SARS_CoV_2:
    fastq1: sample_1__50identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__50identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__70identity_SARS_CoV_2:
    fastq1: sample_1__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__75identity_SARS_CoV_2:
    fastq1: sample_1__75identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__75identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__80identity_SARS_CoV_2:
    fastq1: sample_1__80identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__80identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__85identity_SARS_CoV_2:
    fastq1: sample_1__85identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__85identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__90identity_SARS_CoV_2:
    fastq1: sample_1__90identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__90identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__95identity_SARS_CoV_2:
    fastq1: sample_1__95identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__95identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__100identity_SARS_CoV_2:
    fastq1: sample_2__100identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__100identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__50identity_SARS_CoV_2:
    fastq1: sample_2__50identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__50identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__70identity_SARS_CoV_2:
    fastq1: sample_2__70identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__70identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__75identity_SARS_CoV_2:
    fastq1: sample_2__75identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__75identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__80identity_SARS_CoV_2:
    fastq1: sample_2__80identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__80identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__85identity_SARS_CoV_2:
    fastq1: sample_2__85identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__85identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__90identity_SARS_CoV_2:
    fastq1: sample_2__90identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__90identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__95identity_SARS_CoV_2:
    fastq1: sample_2__95identity_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__95identity_SARS_CoV_2_2.fastq.gz
    tech: illumina
version: '3'
