identification: ''
locus:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
project: flu_100_alt
proteins:
- PB2
- PB1
- PA
- HA
- NP
- locus_00006
- NA
- M
- NS
sample_type: null
samples:
  sample_10_c100_Flu:
    fastq1: sample_10_c100_Flu_1.fastq.gz
    fastq2: sample_10_c100_Flu_2.fastq.gz
    tech: illumina
  sample_11_c100_Flu:
    fastq1: sample_11_c100_Flu_1.fastq.gz
    fastq2: sample_11_c100_Flu_2.fastq.gz
    tech: illumina
  sample_12_c100_Flu:
    fastq1: sample_12_c100_Flu_1.fastq.gz
    fastq2: sample_12_c100_Flu_2.fastq.gz
    tech: illumina
  sample_13_c100_Flu:
    fastq1: sample_13_c100_Flu_1.fastq.gz
    fastq2: sample_13_c100_Flu_2.fastq.gz
    tech: illumina
  sample_14_c100_Flu:
    fastq1: sample_14_c100_Flu_1.fastq.gz
    fastq2: sample_14_c100_Flu_2.fastq.gz
    tech: illumina
  sample_15_c100_Flu:
    fastq1: sample_15_c100_Flu_1.fastq.gz
    fastq2: sample_15_c100_Flu_2.fastq.gz
    tech: illumina
  sample_16_c100_Flu:
    fastq1: sample_16_c100_Flu_1.fastq.gz
    fastq2: sample_16_c100_Flu_2.fastq.gz
    tech: illumina
  sample_17_c100_Flu:
    fastq1: sample_17_c100_Flu_1.fastq.gz
    fastq2: sample_17_c100_Flu_2.fastq.gz
    tech: illumina
  sample_18_c100_Flu:
    fastq1: sample_18_c100_Flu_1.fastq.gz
    fastq2: sample_18_c100_Flu_2.fastq.gz
    tech: illumina
  sample_19_c100_Flu:
    fastq1: sample_19_c100_Flu_1.fastq.gz
    fastq2: sample_19_c100_Flu_2.fastq.gz
    tech: illumina
  sample_1_c100_Flu:
    fastq1: sample_1_c100_Flu_1.fastq.gz
    fastq2: sample_1_c100_Flu_2.fastq.gz
    tech: illumina
  sample_20_c100_Flu:
    fastq1: sample_20_c100_Flu_1.fastq.gz
    fastq2: sample_20_c100_Flu_2.fastq.gz
    tech: illumina
  sample_21_c100_Flu:
    fastq1: sample_21_c100_Flu_1.fastq.gz
    fastq2: sample_21_c100_Flu_2.fastq.gz
    tech: illumina
  sample_22_c100_Flu:
    fastq1: sample_22_c100_Flu_1.fastq.gz
    fastq2: sample_22_c100_Flu_2.fastq.gz
    tech: illumina
  sample_23_c100_Flu:
    fastq1: sample_23_c100_Flu_1.fastq.gz
    fastq2: sample_23_c100_Flu_2.fastq.gz
    tech: illumina
  sample_24_c100_Flu:
    fastq1: sample_24_c100_Flu_1.fastq.gz
    fastq2: sample_24_c100_Flu_2.fastq.gz
    tech: illumina
  sample_25_c100_Flu:
    fastq1: sample_25_c100_Flu_1.fastq.gz
    fastq2: sample_25_c100_Flu_2.fastq.gz
    tech: illumina
  sample_26_c100_Flu:
    fastq1: sample_26_c100_Flu_1.fastq.gz
    fastq2: sample_26_c100_Flu_2.fastq.gz
    tech: illumina
  sample_27_c100_Flu:
    fastq1: sample_27_c100_Flu_1.fastq.gz
    fastq2: sample_27_c100_Flu_2.fastq.gz
    tech: illumina
  sample_28_c100_Flu:
    fastq1: sample_28_c100_Flu_1.fastq.gz
    fastq2: sample_28_c100_Flu_2.fastq.gz
    tech: illumina
  sample_29_c100_Flu:
    fastq1: sample_29_c100_Flu_1.fastq.gz
    fastq2: sample_29_c100_Flu_2.fastq.gz
    tech: illumina
  sample_2_c100_Flu:
    fastq1: sample_2_c100_Flu_1.fastq.gz
    fastq2: sample_2_c100_Flu_2.fastq.gz
    tech: illumina
  sample_30_c100_Flu:
    fastq1: sample_30_c100_Flu_1.fastq.gz
    fastq2: sample_30_c100_Flu_2.fastq.gz
    tech: illumina
  sample_3_c100_Flu:
    fastq1: sample_3_c100_Flu_1.fastq.gz
    fastq2: sample_3_c100_Flu_2.fastq.gz
    tech: illumina
  sample_4_c100_Flu:
    fastq1: sample_4_c100_Flu_1.fastq.gz
    fastq2: sample_4_c100_Flu_2.fastq.gz
    tech: illumina
  sample_5_c100_Flu:
    fastq1: sample_5_c100_Flu_1.fastq.gz
    fastq2: sample_5_c100_Flu_2.fastq.gz
    tech: illumina
  sample_6_c100_Flu:
    fastq1: sample_6_c100_Flu_1.fastq.gz
    fastq2: sample_6_c100_Flu_2.fastq.gz
    tech: illumina
  sample_7_c100_Flu:
    fastq1: sample_7_c100_Flu_1.fastq.gz
    fastq2: sample_7_c100_Flu_2.fastq.gz
    tech: illumina
  sample_8_c100_Flu:
    fastq1: sample_8_c100_Flu_1.fastq.gz
    fastq2: sample_8_c100_Flu_2.fastq.gz
    tech: illumina
  sample_9_c100_Flu:
    fastq1: sample_9_c100_Flu_1.fastq.gz
    fastq2: sample_9_c100_Flu_2.fastq.gz
    tech: illumina
version: ''
