identification: MN908947
locus:
- SARS_CoV_2
project: SARS_CoV_2_500snps
proteins:
- orf1ab
- S
- ORF3a
- E
- M
- ORF6
- ORF7a
- ORF8
- N
- ORF10
sample_type: null
samples:
  sample_10__500snps_SARS_CoV_2:
    fastq1: sample_10__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_10__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_11__500snps_SARS_CoV_2:
    fastq1: sample_11__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_11__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_12__500snps_SARS_CoV_2:
    fastq1: sample_12__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_12__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_13__500snps_SARS_CoV_2:
    fastq1: sample_13__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_13__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_14__500snps_SARS_CoV_2:
    fastq1: sample_14__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_14__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_15__500snps_SARS_CoV_2:
    fastq1: sample_15__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_15__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_16__500snps_SARS_CoV_2:
    fastq1: sample_16__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_16__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_17__500snps_SARS_CoV_2:
    fastq1: sample_17__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_17__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_18__500snps_SARS_CoV_2:
    fastq1: sample_18__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_18__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_19__500snps_SARS_CoV_2:
    fastq1: sample_19__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_19__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_1__500snps_SARS_CoV_2:
    fastq1: sample_1__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_1__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_20__500snps_SARS_CoV_2:
    fastq1: sample_20__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_20__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_21__500snps_SARS_CoV_2:
    fastq1: sample_21__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_21__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_22__500snps_SARS_CoV_2:
    fastq1: sample_22__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_22__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_23__500snps_SARS_CoV_2:
    fastq1: sample_23__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_23__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_24__500snps_SARS_CoV_2:
    fastq1: sample_24__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_24__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_25__500snps_SARS_CoV_2:
    fastq1: sample_25__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_25__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_26__500snps_SARS_CoV_2:
    fastq1: sample_26__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_26__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_27__500snps_SARS_CoV_2:
    fastq1: sample_27__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_27__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_28__500snps_SARS_CoV_2:
    fastq1: sample_28__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_28__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_29__500snps_SARS_CoV_2:
    fastq1: sample_29__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_29__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_2__500snps_SARS_CoV_2:
    fastq1: sample_2__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_2__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_30__500snps_SARS_CoV_2:
    fastq1: sample_30__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_30__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_3__500snps_SARS_CoV_2:
    fastq1: sample_3__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_3__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_4__500snps_SARS_CoV_2:
    fastq1: sample_4__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_4__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_5__500snps_SARS_CoV_2:
    fastq1: sample_5__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_5__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_6__500snps_SARS_CoV_2:
    fastq1: sample_6__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_6__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_7__500snps_SARS_CoV_2:
    fastq1: sample_7__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_7__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_8__500snps_SARS_CoV_2:
    fastq1: sample_8__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_8__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
  sample_9__500snps_SARS_CoV_2:
    fastq1: sample_9__500snps_SARS_CoV_2_1.fastq.gz
    fastq2: sample_9__500snps_SARS_CoV_2_2.fastq.gz
    tech: illumina
version: '3'
